### ISSUE TITLE
Results are outdated.

### ISSUE THREAD

**Issue by antoniormrzz** [npms-io/npms-api#101]
This api returns 2 packages for me, I have 4. You can try with more users, namely sindresorhus has more than 1k but this api shows around 950.

**Comment by joebochill** [comment]
I'm seeing the same thing across a bunch of my packages. The data coming back appears to be several months old.

**Comment by dobladov** [comment]
I encountered the same problem for some popular packages:

**webpack**: https://api.npms.io/v2/package/webpack
Current version: [5.34.2](https://www.npmjs.com/package/webpack)
API version: `4.44.2`

**typescript**: https://api.npms.io/v2/package/typescript
Current version: [4.2.2](https://www.npmjs.com/package/typescript)
API version: `3.4.3`

`AnalyzedAt` value seems to be several months old, how often does the API updates?
