### ISSUE TITLE
Get package info should support scope

### ISSUE THREAD

**Issue by atian25** [npms-io/npms-api#102]
https://api.npms.io/v2/package/@vue/cli  is 404

cc @satazor

**Comment by atian25** [comment]
https://api.npms.io/v2/package/%40vue%2Fcli

**Comment by Lonli-Lokli** [comment]
@atian25 Seems like it does not always work
https://api.npms.io/v2/package/%40lonli-lokli%2Fts-result

https://www.npmjs.com/package/@lonli-lokli/ts-result

**Comment by atian25** [comment]
https://npms.io/search?q=%40lonli-lokli%2Fts-result

maybe should report to `npms.io`
