### ISSUE TITLE
Api Endpoint Returns An Error Response

### ISSUE THREAD

**Issue by SasheVuchkov** [npms-io/npms-api#107]
Hello,

I use your API to fetch statistics about my simple library. Once fetched, they are displayed on the library's landing page.

Yesterday I noticed that all stats are missing, and after some debugging, I found out that the following endpoint returns an error:

Endpoint:

`https://api.npms.io/v2/package/near-duplicate-docs`

Response: 

`{"code":"INTERNAL","message":"Internal server error"}`

Best Regards,
Sashe Vuchkov

**Comment by satazor** [comment]
Should be good now. There will be some 404s in the /package endpoint for a couple of days, because the couchdb database is being re-analyzed. Sorry for the inconvenience.

**Comment by SasheVuchkov** [comment]
> Should be good now. There will be some 404s in the /package endpoint for a couple of days, because the couchdb database is being re-analyzed. Sorry for the inconvenience.

Thanks :)
