### ISSUE TITLE
The 'package/mget' API get the missing data

### ISSUE THREAD

**Issue by fanker** [npms-io/npms-api#108]
`eq`: 
url: https://api.npms.io/v2/package/mget
method: post
params: ["axois","immer","lodash"]

`curl -H "Content-type: application/json" -X POST -d '["axois","immer","lodash"]' https://api.npms.io/v2/package/mget`

`result`:
the package of axois's collected data miss `github` and `source` key

**Comment by satazor** [comment]
@fanker `axois` has been taken over by `npm` because the name conflicts with `axios`: https://api.npms.io/v2/package/axois

Check it's repository field.
