### ISSUE TITLE
Open API to public?

### ISSUE THREAD

**Issue by dcrockwell** [npms-io/npms-api#23]
Perhaps some feasibility research would be best to start out with, as the costs involved with serving up these search results will eventually become unmanageable.

I'd like for users of my modular system to use a command-line utility to search npms and return results based upon keywords. Currently, they must use the npmjs.com search which tears them away from the terminal.

**Comment by satazor** [comment]
> Perhaps some feasibility research would be best to start out with, as the costs involved with serving up these search results will eventually become unmanageable.

We have not make it publicly available yet because it's not finalised and it's undocumented. This means that we may change the responses structure until then.

> I'd like for users of my modular system to use a command-line utility to search npms and return results based upon keywords. Currently, they must use the npmjs.com search which tears them away from the terminal.

One of our goals is to build a [CLI](https://github.com/npms-io/npms-cli) program, similar to `npm search` that uses our API. Would you be interested in contributing?

**Comment by dcrockwell** [comment]
> We have not make it publicly available yet because it's not finalised and it's undocumented. This means that we may change the endpoints and responses structure until then.

This could be solved elegantly with an intermediate SDK layer that both the official client and all other clients can connect with (Including the CLI below).

> One of our goals is to build a CLI program, similar to npm search that uses our API. Would you be interested in contributing?

Perhaps. I have a lot of experience with CLI applications and testing them, but we'd need to agree upon an approach before we go butting heads against each other :)

**Comment by dcrockwell** [comment]
For example, the project will need to agree upon standards for:

* linting rules
* test runner
* assertion style
* quality services
  * bithound, codeclimate, etc.
* workflow management (gitflow?)
* test structure
  * one assertion per test? multiple assertions per test?
  * BDD or TDD?

This is just the beginning of the conversation, really.

**Comment by dcrockwell** [comment]
Perhaps a new issue for discussion of standards is in order.

**Comment by satazor** [comment]
We should create a new issue in the npms-api repository itself and discuss there.

**Comment by satazor** [comment]
See: https://github.com/npms-io/npms-cli/issues/1
