### ISSUE TITLE
Return better suggestions for mis-spelled queries

### ISSUE THREAD

**Issue by mshenfield** [npms-io/npms-api#40]
[npms.io](npms.io) should provide helpful near matches suggestsions for transposed or mis-spelled searches. For example, search for "bootstrp" has suggestions on [npmjs.org](npmjs.org), but none for npms.

<img width="813" alt="npms-bootstrp-suggestions" src="https://cloud.githubusercontent.com/assets/4812055/17388205/33574c18-59c0-11e6-9b44-85da6519a39e.png">
<img width="714" alt="npmjs-bootsrp-suggestions" src="https://cloud.githubusercontent.com/assets/4812055/17388217/482fd2a4-59c0-11e6-90e0-cacf69d8964f.png">

To accomplish, [the query](https://github.com/npms-io/npms-api/blob/master/lib/routes/search/suggestions.js) that powers the [`/search/suggestions`](https://api-docs.npms.io/#api-search-suggestions) would need to be modified.

**Comment by satazor** [comment]
@atduarte what's your opinion on this?

**Comment by satazor** [comment]
Bump @atduarte

**Comment by atduarte** [comment]
I don't know... In my opinion, as expressed earlier in other issues, this kind of search should have as little magic to do the match, since it's frequent to look for an exact word and not for the related ones (express vs expression, jquery vs query, got vs get, ...)

**Comment by satazor** [comment]
I agree. We can revisit this if other people complain about the same. Closing.
