### ISSUE TITLE
Find packages by keyword

### ISSUE THREAD

**Issue by sindresorhus** [npms-io/npms-api#42]
It's a very common need to be able to find packages according to one or more keywords.

It is possible with the [npm API](https://github.com/sindresorhus/npm-keyword), but it's undocumented, slow, and you can only fetch by one keyword at the time.

You already have the data, so would be nice to expose a keyword API endpoint.

**Comment by satazor** [comment]
Agreed.

**Comment by satazor** [comment]
@sindresorhus How do you expect the keywords matching to happen? Exact match or some degree of fuzziness similar to the search term?

**Comment by satazor** [comment]
@sindresorhus please answer on #29, closing this as duplicate

**Comment by sindresorhus** [comment]
Exact. I would like to find, for example, all packages with the keyword `gulpplugin`. I wouldn't want grunt tasks to show up then, just because they have the `gruntplugin` keyword, which is very close.

**Comment by satazor** [comment]
@sindresorhus Aright, will do exact match.

**Comment by satazor** [comment]
@sindresorhus another question, if you specify multiple keywords do you expect the operator to be AND or OR?

**Comment by sindresorhus** [comment]
Hard to say. I can't think of when I would need multiple keywords at all. I guess if you really want it and there has to be only one of those operators, I would go with `OR`, as it's unlikely many packages has the same multiple keywords.

**Comment by satazor** [comment]
Agree, thanks for the feedback!
