### ISSUE TITLE
Index @types/xxx packages

### ISSUE THREAD

**Issue by IOAyman** [npms-io/npms-api#46]
Type definition packages for TypeScript, like [@types/validator](https://www.npmjs.com/package/@types/validator), don't seem to be indexed at all!

![screenshot_2016-09-20_13-35-49](https://cloud.githubusercontent.com/assets/6185849/18670321/a38b4e7c-7f3f-11e6-87d3-16331049bae2.png)

**Comment by satazor** [comment]
Duplicate, see https://github.com/npms-io/npms-analyzer/issues/47
