### ISSUE TITLE
Make the api wide-open

### ISSUE THREAD

**Issue by sasha240100** [npms-io/npms-api#47]
Hello, develop a [plugin registry](https://github.com/WhitestormJS/plugins) for my project. And i would like to know if there is a way to **run npms-api with openshift**. I need this because your API can't be used from localhost.
Thanks in advance!

**Comment by satazor** [comment]
@sasha240100 the API can absolutely run on localhost but it needs a couchdb database and elasticsearch filled with the `npms-analyzer` data.

**Comment by sasha240100** [comment]
@satazor I mean that if i will try to make an ajax request it will result with such error:
![image](https://cloud.githubusercontent.com/assets/7657429/18818592/d7a8ffd4-8385-11e6-9817-8c221210841f.png)

**Comment by satazor** [comment]
Oh that's  CORS problem. The API is not currently wide-open, it only allows origins that match `*.npms.io`. We can either lift this security measure or you can implement a proxy.

//cc @atduarte what are your thoughts? Opening the API will make it vulnerable against DDoS attacks, specially on sites that have high traffic and want to harm npms.io for some reason.

**Comment by sasha240100** [comment]
@satazor I will try proxy, but IMO it's better to open API (i personally promise not to make DDOS attacks :D)
Please, ping me if you decide to open API.

P.s.: Still no success with making an api server with openshift. That's all i've done: http://plugins-whsjs.rhcloud.com/

**Comment by satazor** [comment]
@sasha240100 how did you setup the proxy?

**Comment by sasha240100** [comment]
@satazor What proxy?

----

All i can tell you is that final problem was this:
![photo_2016-09-26_01-31-07](https://cloud.githubusercontent.com/assets/7657429/18818701/1739879c-8389-11e6-8055-753cf25e8a14.jpg)

**Comment by satazor** [comment]
@sasha240100 nvm I though you created a proxy to circumvent the CORS issue. Lets wait for @atduarte opinion before deciding on wide-opening the API.

**Comment by mikeerickson** [comment]
@satazor If you don't want to open the API (which makes good sense) how about using token based access (this is how I personally setup my APIs)

**Comment by preco21** [comment]
@satazor Hmm, maybe you guys can also consider about [CloudFlare](https://www.cloudflare.com/). It provides DDOS protection (not sure about for APIs) and caching features.

@sasha240100 Seems he meant Reverse Proxy (such [CORS anywhere](https://www.npmjs.com/package/cors-anywhere) like).

Open API to widely +1

**Comment by satazor** [comment]
@preco21 we already use CF. At the moment, the API does not send any cache headers upstream and no caching rules are configured. We can start sending cache headers though, 1m or more.

@mikeerickson we will definitively need that once we integrate with GitHub to give a more personalised search experience, but for now it would introduce complexity for little benefit.

I think it's reasonable to wide-open the API.. I don't think anyone would put a script into a high traffic website just to harm npms.io.. If that ever happens, we can consider re-enabling the CORS and add cache headers so that CF handles most traffic for us.

**Comment by atduarte** [comment]
I also think we can open it and think about changing the cache headers (CF). An open source project like this being attacked would be unusual.

**Comment by satazor** [comment]
I've wide-open the API, @sasha240100 let me know if it's now working for you. I'll add cache headers if we get high load.

**Comment by sasha240100** [comment]
@satazor Thanks! I will try once i'm at home

**Comment by sasha240100** [comment]
Works awesome thanks!

**Comment by wtgtybhertgeghgtwtg** [comment]
When using fetch, the CORS-preflight fetch for `mget` seems to be returning a 404, presumably because of the OPTIONS method.  Is fetch not supported?

**Comment by satazor** [comment]
@wtgtybhertgeghgtwtg can you open a new issue specific to that? Thanks

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry about that.  Issue #60.
