### ISSUE TITLE
Search query: if use "-" in keywords filter - plugins are not listed. [Bug]

### ISSUE THREAD

**Issue by sasha240100** [npms-io/npms-api#48]
Basically, when you try to search `keywords:gulp-util` or `keywords:whs-component` it returns empty list. **Each keyword with "-" symbol doesn't work.**
IMO it is a bug, and i would like to help to solve it (if you don't have a time), just point me where should i look. 

![image](https://cloud.githubusercontent.com/assets/7657429/18838187/28813636-840f-11e6-8082-d69b95fc1771.png)

**Comment by sasha240100** [comment]
I thinks it's because of camelCase on this line: https://github.com/npms-io/npms-api/blob/master/lib/util/parseQuery.js#L56

**Comment by satazor** [comment]
@sasha240100 that's not the problem because it's only camelcasing the keys not the values. Do you know which packages have the keywords you mentioned?

**Comment by sasha240100** [comment]
@satazor 
![image](https://cloud.githubusercontent.com/assets/7657429/18846438/8f080e74-842e-11e6-8c1f-10e01cb61cf0.png)
![image](https://cloud.githubusercontent.com/assets/7657429/18846449/9b7b4874-842e-11e6-988c-987922a232b7.png)

**Comment by satazor** [comment]
@sasha240100 I've found the issue and I'm currently fixing it. Will let you know once done.

**Comment by satazor** [comment]
Fixed, thanks for reporting.

**Comment by sasha240100** [comment]
@satazor Nice work. Thanks!
