### ISSUE TITLE
Can't find some modules like `@blueprintjs/core` or `whs`

### ISSUE THREAD

**Issue by michaelrambeau** [npms-io/npms-api#56]
Hello,
First thank you very much for the great API you created, I use it in http://bestof.js.org/ and it works very well.
My only problem is that I cannot find the following modules calling the API:

* https://www.npmjs.com/package/%40blueprintjs%2Fcore
* https://www.npmjs.com/package/choreographer-js
* https://www.npmjs.com/package/whs

I got `Module not found` errors if I call the following URLs:

* https://api.npms.io/module/@blueprintjs/core or https://api.npms.io/v1/module/%40blueprintjs%2Fcore
* https://api.npms.io/module/choreographer-js
* https://api.npms.io/module/whs

...but I can find them using the web UI (for example: https://npms.io/search?q=whs)

Is there something I am doing wrong ? Should I format the module names in a specific way ?

Thank you in advance!

**Comment by satazor** [comment]
@michaelrambeau Thanks!

You are using the old API version which is deprecated and will be removed in December.

Using the new version it works correctly: https://api.npms.io/v2/package/%40blueprintjs%2Fcore
Check out the API changelog: https://github.com/npms-io/npms-api/blob/master/CHANGELOG.md

Have fun!

**Comment by michaelrambeau** [comment]
Thank you very much @satazor , it works, I got a correct response for more than 560 projects.

Keep up moving forward!

**Comment by satazor** [comment]
@michaelrambeau <3
