### ISSUE TITLE
404 on CORS-preflight fetch.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [npms-io/npms-api#60]
When using fetch, the CORS-preflight fetch for mget seems to be returning a 404, presumably because of the OPTIONS method. Is fetch not supported?

**Comment by satazor** [comment]
It should be but I guess `nginx` is not correctly configured. I'm busy now but I will take on this tonight. Could you paste here the CURL command so that it's easier for me? Thanks.

**Comment by wtgtybhertgeghgtwtg** [comment]
`curl "https://api.npms.io/v2/package/mget" -X OPTIONS -H "pragma: no-cache" -H "access-control-request-method: POST" -H "origin: http://localhost:3000" -H "accept-encoding: gzip, deflate, sdch, br" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36" -H "accept: */*" -H "cache-control: no-cache" -H "authority: api.npms.io" -H "referer: http://localhost:3000/" -H "access-control-request-headers: content-type" --compressed`

**Comment by satazor** [comment]
I'm afraid I can't work on this today, will have to be tomorrow.

**Comment by satazor** [comment]
@wtgtybhertgeghgtwtg should be working! Please confirm. :)

**Comment by wtgtybhertgeghgtwtg** [comment]
The response gives the following message.
```
Fetch API cannot load https://api.npms.io/v2/package/mget. Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```
Attempting it without defining content-type resultings in a 400.

**Comment by satazor** [comment]
Oh, give me a sec.

**Comment by satazor** [comment]
Can you test it now? Does it work?

**Comment by wtgtybhertgeghgtwtg** [comment]
Here is a JSFiddle: https://jsfiddle.net/52Ltk9hf/

**Comment by wtgtybhertgeghgtwtg** [comment]
Oddly enough, it seems to work in Edge, but not Chrome.  I do not think this is a problem with `npms-io`.  Sorry about that.

**Comment by satazor** [comment]
@wtgtybhertgeghgtwtg Thanks for the fiddle, it's now working. Just leave a comment if there's something else to be fixed.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you very much.
