### ISSUE TITLE
Get specific version of package.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [npms-io/npms-api#61]
There does not seem to be a way to get specific versions of a package.  Is this not supported?

**Comment by satazor** [comment]
No, only the last one is available atm.

**Comment by wtgtybhertgeghgtwtg** [comment]
Is there anything I can do to help make this possible?

**Comment by satazor** [comment]
@wtgtybhertgeghgtwtg can you elaborate on why you need this? What are you building?

**Comment by wtgtybhertgeghgtwtg** [comment]
I am trying to map a dependency graph.  But a package may depend on a version of another package other than the latest version.  Specifically, I would need to be able to resolve a version string, like the kind you would see in `collected.metadata.dependencies`.

**Comment by satazor** [comment]
I see, well there's no way to do that now. I don't really want to introduce complexity now, the analyzer is quite complex as it is now. Still, you may look at the official npm registry to do what you want.
