### ISSUE TITLE
Result limit is 250 packages

### ISSUE THREAD

**Issue by gismo141** [npms-io/npms-api#64]
How could I get the next packages, when I need all the results for the given query?

**Comment by satazor** [comment]
You can read the api docs here https://api-docs.npms.io/. Does it answer your question?

**Comment by gismo141** [comment]
Offset and limit? Sorry but somehow I am unable to find these parameters documented on that page...

**Comment by atduarte** [comment]
See `from` and `size`.

**Comment by satazor** [comment]
![screen shot 2016-12-13 at 5 00 12 pm](https://cloud.githubusercontent.com/assets/1017236/21151050/0eb8e15e-c159-11e6-9802-57348c87b207.png)

**Comment by satazor** [comment]
Oops, the params are actually `from` and `size`. My mistake. Can this be closed?

**Comment by gismo141** [comment]
Oh yes sorry! Somehow I was blind, thank you very much! ;)

**Comment by satazor** [comment]
No problem!
