### ISSUE TITLE
Querying a big page number returns HTTP status 500

### ISSUE THREAD

**Issue by mbektchiev** [npms-io/npms-api#65]
Results from big page numbers cannot be retrieved from the `search` endpoint. To reproduce it try these two requests:

* https://api.npms.io/v2/search?q=a&from=2000&size=10 works correctly: reports 98331 total results and returns 10 of them.
* https://api.npms.io/v2/search?q=a&from=22000&size=10 returns Internal Server Error.

**Comment by warent** [comment]
I've encountered the same thing. `https://api.npms.io/v2/search?q=not:insecure&from=9975` works, but `https://api.npms.io/v2/search?q=not:insecure&from=9976` returns a 500. Seems the API can't page to 10k results
