### ISSUE TITLE
Hosted API down

### ISSUE THREAD

**Issue by bbarwick-fdg** [npms-io/npms-api#69]
The API for the main site is returning `Internal Server Error`: 
https://api.npms.io/v2/search?from=0&q=react&size=25

**Comment by satazor** [comment]
Thanks for the report. I'm unable to ssh into the machine, it seems it has died. I've contacted the support and I'm still waiting for a response.

**Comment by jcrimp** [comment]
I see that https://api.npms.io/v2/search?from=0&q=react&size=25 is no longer returning `Internal server error`. 
However, https://api.npms.io/v2/package/request is still returning `Internal server error`.
I understand you may still be waiting on a response from support, but wanted to call attention to the error from https://api.npms.io/v2/package/request in case it is new information.

**Comment by satazor** [comment]
The state of the disk is read-only which makes couchdb to error out. Still waiting for the support to respond.

**Comment by mraible** [comment]
@satazor Do you need help with hosting costs for this project? My company might be willing to sponsor.

**Comment by satazor** [comment]
All should be good now.

@mraible That would be great, currently I'm paying this from my own money. You can contact me via email, see my profile.

**Comment by jdubois** [comment]
Oh @satazor I thought this was official from NPM? If @mraible doesn't find a solution, you can also ask me

**Comment by satazor** [comment]
They are using the software but on their own infrastructure.

**Comment by deepu105** [comment]
That sucks, they could have atleast sponsored you
