### ISSUE TITLE
wrong daily downloads count

### ISSUE THREAD

**Issue by DanielRuf** [npms-io/npms-api#70]
It seems the data for downloads and other metrics are not showing the latest data.

https://api.npms.io/v2/package/tailwindcss shows downloads data for the 15th of December with a count of 0.

**Comment by satazor** [comment]
@DanielRuf a package is only analyzed once publish or once every 15 days.

**Comment by DanielRuf** [comment]
Please compare it to the tachyons package which has fresh data.

Is this infomation written somewhere?

**Comment by DanielRuf** [comment]
Also 0 downloads for the given day seems to be wrong imo.

**Comment by satazor** [comment]
It’s written here: https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md#observers

The exact time is not specified because it’s configurable and might change to accommodate the growth of the registry without having more machines to run the analyzer.

**Comment by satazor** [comment]
The number of downloads is 0 for the first day but it shows non 0 for the subsequent range of days. We just use the npm API to fetch the downloads count. If you feel that is wrong, either we are reading it’s info in a wrong manner or the API response is already incorrect. Please debug and leave the feedback here.

**Comment by DanielRuf** [comment]
> It’s written here: https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md#observers

Thanks.

Well, let's see what happens after the 30th. Would have been good to find the info on the website.

**Comment by DanielRuf** [comment]
I guess the downloads are reset for new releases but do not incorporate the downloads of the previous releases on the same day (think about projects with lock files which use previous versions).

**Comment by DanielRuf** [comment]
https://api.npmjs.org/downloads/point/2017-12-26/tailwindcss

https://api.npmjs.org/downloads/point/2017-12-27/tailwindcss

daily is the previous day so the data of the current day always gives 0.

**Comment by DanielRuf** [comment]
https://github.com/npm/download-counts#data-source

**Comment by satazor** [comment]
@bcoe I guess this changed from the most recent API changes that you made?

**Comment by DanielRuf** [comment]
It seems stars, issues (and deps) seem to be wrong for `angular`, `angularjs` and so on or what name is used for angular core?

**Comment by jansepke** [comment]
the same happens to react (https://api.npms.io/v2/package/react) the github property is completely  missing from the response, could this be the reason?

**Comment by sharikovvladislav** [comment]
same for dependentsCount

> @DanielRuf a package is only analyzed once publish or once every 15 days.
react was analyzedAt 2019-09-03T02:39:30.064Z . more then a month ago: https://api.npms.io/v2/package/react
