### ISSUE TITLE
Retrieving records more than 5000 records

### ISSUE THREAD

**Issue by abishekrsrikaanth** [npms-io/npms-api#73]
Currently the Search API Endpoint `https://api-docs.npms.io/` only allows a maximum of **5250** records with its `from` and `size` parameters. Is there an authenticated way to retrieve more records using the `search` endpoint

**Comment by albinekb** [comment]
I'm guessing you can fetch the next page by offsetting `from` with the amount of items you received in the first call?

**Comment by kategengler** [comment]
I'd also like to be able to fetch more than 5000 results. I run EmberObserver.com which lists & curates all Ember addons (npm packages with `ember-addon` keyword). I'd like to use npms.io API to fetch the list of addons with the keyword, but the number of addons has just edged over 5000.

**Comment by satazor** [comment]
You can use the from and size query params.

Docs here: https://api-docs.npms.io/

**Comment by satazor** [comment]
Hmmm you want the ability to specify more than 5000 in the `from` field correct?

Could you please make a PR to increase the value?

**Comment by kategengler** [comment]
Can absolutely PR that; seemed like a policy decision.

**Comment by satazor** [comment]
It is, the more records we go deeper the more memory the query will use. Let’s increase it to 10000 and see how it plays out.
