### ISSUE TITLE
Can it create a third party registry api ?

### ISSUE THREAD

**Issue by lefreet** [npms-io/npms-api#80]
I have a third party registry created by ProGet.

And have some way to use the npm-api and packages data from my packages registry ?

**Comment by satazor** [comment]
Hello @lefreet

It's certainly possible but you would have to run npms on your own infrastructure, configured for that registry. If that's something you want to do, let me know so that I can help you.

**Comment by lefreet** [comment]
@satazor I guess that whether the npm offical registry(https://registry.npmjs.org/) or a third party registry(http://pkgs.istrongcloud.com/npm/registry/) of my team， they have same port and service protocol， so I can run `npm install` both side.   so， is there have some config in `npms-api`， that i only rewrite the registry params in fronted end， and it toggle the packages source to the registry i wanted? thanks.

**Comment by satazor** [comment]
@lefreet Unfortunately no. The npms-api is just a thin consumer of a elasticsearch index built by npms-analyzer. This means that you must be run npms-analyzer on that registry.

Having the API analyze stuff in real-time or on-demand would be pretty slow.

**Comment by satazor** [comment]
Glad to clarify.
