### ISSUE TITLE
Not returning any new packages created in the last month?

### ISSUE THREAD

**Issue by rdlauer** [npms-io/npms-api#81]
It looks like the api isn't returning anything new - and hasn't for about a month. Can someone give a status update please?

**Comment by glennsl** [comment]
I would very much like to know this as well. I appreciate all the effort that have gone into making this, and I hope I don't come across as demanding in any way, but I made the choice a while back to depend on this API for the [Reason Package Index](https://redex.github.io/), and if in the worst case this has been abandoned, or if we should just expect unreliable service, we will have to make some significant changes and would like to know as soon as possible.

**Comment by satazor** [comment]
Should be fixed. I had to migrate to a machine with more storage but took longer than expected due to I being overwhelmed with other stuff.

Thanks for the heads up.

**Comment by rdlauer** [comment]
Thanks!
