### ISSUE TITLE
Indexing has stopped again

### ISSUE THREAD

**Issue by glennsl** [npms-io/npms-api#85]
No new or updated packages seems to have been indexed for the past week. Is the service down again?

Pinging @satazor due to the urgency.

**Comment by satazor** [comment]
Can you please give an example of the package so that I can debug?

**Comment by wyze** [comment]
One example is `bs-tinycolor`. It is on npm here: https://www.npmjs.com/package/bs-tinycolor with 2 versions published, first one 7 days ago. It does not appear in results on npms.io at all.

**Comment by glennsl** [comment]
Sure, here's one:
https://www.npmjs.com/package/bs-tinycolor - https://npms.io/search?q=bs-tinycolor

There's also bs-music-theory and bs-marky-markdown, which are new, and bs-jest-dom which has been updated, but none have been (re)indexed. Nothing seems to get reindexed

**Comment by satazor** [comment]
The observer process crashed and pm2 list was unable to restart it for some reason. The process was manually restarted and should catch up during the next days. The situation should be eventually normalized.

**Comment by glennsl** [comment]
Looks good now. Thanks!
