### ISSUE TITLE
[BUG] The API is down

### ISSUE THREAD

**Issue by spersico** [npms-io/npms-api#86]
Since... today I think?
Tested:
```https://api.npms.io/v2/search?q=cross+spawn```
```https://api.npms.io/v2/package/react```
```https://api.npms.io/v2/package/mget (with body ["cross-spawn", "react"] )```

They all respond
```
{
    "code": "INTERNAL",
    "message": "Internal server error"
}

**Comment by satazor** [comment]
Fixed! Thanks for reporting. Elastisearch crashed and systemd was unable to restart it for some reason.
