### ISSUE TITLE
Indexing seems to be down again

### ISSUE THREAD

**Issue by glennsl** [npms-io/npms-api#90]
Seems like indexing has been down for over a month now. Some examples:

https://www.npmjs.com/package/bs-diffie-hellman vs https://npms.io/search?q=bs-diffie-hellman

and 

https://www.npmjs.com/package/reason-react-native-netinfo vs https://npms.io/search?q=reason-react-native-netinfo

cc @satazor

**Comment by satazor** [comment]
Hello!

I've triggered the manual analysis of these packages. The analyzer process somehow wasn't initiated by pm2 upon a restart made some weeks ago.

**Comment by glennsl** [comment]
Thanks for the quick action! I can confirm that these two have now been indexed. I have a bunch of others as well, but I can wait to see if they get picked up and confirm it's back to normal again.

**Comment by glennsl** [comment]
Everything seems to be in order now, except this one, which failed with an "EMFILE" error that apparently means too many files were open:

https://api.npms.io/v2/package/bs-jest-date-mock

Do you think you could retrigger that again to see if's a transient error?
