### ISSUE TITLE
Some newly published packages not getting indexed

### ISSUE THREAD

**Issue by glennsl** [npms-io/npms-api#91]
Could you check these out @satazor?

https://www.npmjs.com/package/relude-eon | https://npms.io/search?q=relude-eon
https://www.npmjs.com/package/reason-date-fns | https://npms.io/search?q=reason-date-fns

**Comment by rdlauer** [comment]
It looks like indexing is down again @satazor ?

**Comment by sharikovvladislav** [comment]
Looks like I am getting the same: https://twitter.com/sharikov_vlad/status/1184890777463336960?s=20

I can see that analyzedAt is somewhere far far in the past.

https://api.npms.io/v2/package/react `"analyzedAt": "2019-09-03T02:39:30.064Z"`
https://api.npms.io/v2/package/debug `"analyzedAt": "2019-09-05T08:13:56.486Z",`

Any information?

**Comment by sharikovvladislav** [comment]
Both packages updated today.

**Comment by satazor** [comment]
There was a replication error due to a miss configuration, I’ve fixed it yesterday. Some packages might take longer to recover. Thanks for reporting.
