### ISSUE TITLE
Sub-module Package Search

### ISSUE THREAD

**Issue by jordan-mcrae** [npms-io/npms-api#98]
Hi there,

I have come across a few repos that are broken down into sub-modules. For example, "@zendeskgarden/react-avatars". Is there a way that I can get the details on a package like this?

NPM url: https://www.npmjs.com/package/@zendeskgarden/react-avatars

Example call that returns an error: https://api.npms.io/v2/package/@zendeskgarden/react-avatars

Thank you!

**Comment by roojay520** [comment]
You just need `encodeURIComponent('@zendeskgarden/react-avatars')`  this package name. 

Like this: 
[https://api.npms.io/v2/package/%40zendeskgarden%2Freact-avatars](https://api.npms.io/v2/package/%40zendeskgarden%2Freact-avatars)

**Comment by satazor** [comment]
Thanks @roojay520, that's right! Hope that helps @jordan-mcrae
